language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
before_install:
- python -m pip install --upgrade pip
install:
- pip install -r requirements.txt

deploy:
  provider: pypi
  username: __token__
  password:
    secure: MJIssHMh3TWCd+ugSFSYmT6S4ACSwKdhDM9FfaMp+WNOJUT+lFSR2DNoIXjcDHEYpIQZM+g7sfvpqS+iUTX3rk4E131fwwkRygVj8XsPccX1zjtDjyGyQObotTlCvH6JNBQwLXrQbBnusQgkFT6CU7eGE0EvkXMuOI4iY38hhTnEBjl6EmJ4CEEOFXL2DJWmAamAAK3eUN3B6wYDjd37JewULGI7U/Y/kFC/qMxKI/PR+vwgmNkdRgDfJAEdaY+WK0KDotMRekV+YN124A1z4L1A7QawjSuRFIWxF1vVD1EUkbCx8q/1guOtackpkaMFMJHtPAhcNQQ8okTynWusBZbgEHrkspTdIZ6J4dvkDQCm67fjWG+7/dwzR+GsbzJepiuPigi4VPD6/zXL+1zft2jTBoLb9PTnTSRys0RmGvZM0gVjSvzo61Hmbo4COtYR2NlZEa7QV7zrFIzHFwepxK7FlPYX5kW03UKC5pg0WOyrmIp1msyCcIUFeCdkJsRZPnKhihR8J/hFGOcXGuQwejbAYKEldHk2t8WLKqN0K/JaG64Q/ojYZwh/yfaKpEFJfPChutragIXuiipeyvpZDljnlzs+GEvTvVvkn6CHy8aFz169tY1HvUm78IueENWxouIsxqvNe9OftRLdgf4Wn7rYgzdCH3eA4hc7/cjCakc=
  on:
    tags: true
    branch: master