iterations: 100
mc: true
model:
  bounds:
    P_ethanol_p_0: (0.001, 10)
    P_ethanol_y_P: (0.01, 10)
    S_GlcEq_km: (1e-06, 100)
    S_GlcEq_qsmax: (1e-06, 50)
    S_GlcEq_s_0: (1e-06, 150)
    X_0: (0.001, 10)
    y_BM: (0.001, 3)
  model_name: Dynamic Monod model (1 substrate, 1 product)
  parameters_to_estimate:
    P_ethanol_p_0: 1
    P_ethanol_y_P: 1
    S_GlcEq_km: 1
    S_GlcEq_qsmax: 1
    S_GlcEq_s_0: 100
    X_0: 1
    y_BM: 1
path_to_data: C:\Users\millard\Documents\GIT\PhysioFit\data_test\config_file.yml
sds:
  P_ethanol: 3
  S_GlcEq: 7
  X: 1
