name: Build and publish python package to test pypi

on: [push]

jobs:
  publish-service-client-package:
    runs-on: ubuntu-latest
    steps:
      - name: Publish PyPi package
        uses: code-specialist/pypi-poetry-publish@v1
        with:
          PYTHON_VERSION: "3.10"
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_REGISTRY_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
          PUBLISH_REGISTRY: "https://test.pypi.org/legacy/"
